steps:
  - name: python:3.12
    entrypoint: pip
    args: ['install', '-r', 'backend/requirements.txt']
  - name: python:3.12
    entrypoint: python
    args: ['-m', 'pytest', 'backend/tests/', '-v']
    dir: '.'
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/a7system-api', './backend']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/a7system-api']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'a7system-api', '--image', 'gcr.io/$PROJECT_ID/a7system-api', '--region', 'southamerica-east1', '--platform', 'managed']
